 # This is a basic workflow to help you get started with Actions

name: Build and Release Data Pack

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v2.1.3, etc.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Create zip archive
        run: |
          zip -r "${REPO_NAME}.zip" data pack.mcmeta

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.REPO_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
